# Setup
title: Mert Nesvat
url: https://mertnesvat.com
paginate: 2
baseurl: ""
permalink: pretty

# Name of your site (displayed in the header)
name: Mert Nesvat

# Short bio or description (displayed in the header)
description: Experimenting with mobile apps. 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://pbs.twimg.com/profile_images/1313236138488987652/C3hTFTyo_400x400.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Mert Nesvat
  url: https://twitter.com/mertnesvat
  email: mertnesvat@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about
